version: "3"
services:
  db_seg_1:
    image: greenplum:6
    build: .
    container_name: db_seg_1
    hostname: db_seg_1
    command: tail -f /dev/null
    environment:
      - GP_NODE=segment
    volumes:
      - gpdb1:/var/lib/gpdb/data
    networks:
      - gpdb
  db_seg_2:
    image: greenplum:6
    build: .
    container_name: db_seg_2
    hostname: db_seg_2
    command: tail -f /dev/null
    environment:
      - GP_NODE=segment
    volumes:
      - gpdb2:/var/lib/gpdb/data
    networks:
      - gpdb
  db_master_1:
    image: greenplum:6
    build: .
    container_name: db_master_1
    hostname: db_master_1
    command: tail -f /dev/null
    environment:
      - GP_NODE=master
      - HOSTFILE=multihost
    volumes:
      - gpdb0:/var/lib/gpdb/data
    ports:
      - "5432:5432"
    depends_on: 
      - db_seg_1
      - db_seg_2
    links:
      - db_seg_1:seg1
      - db_seg_2:seg2
    networks:
      - gpdb

networks:
  gpdb:

volumes:
  gpdb0:
  gpdb1:
  gpdb2:
